---
- hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: Installing Unzip
    yum:
     name: unzip
     state: latest

  - name: Downloading TomcatServer....
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.23/bin/apache-tomcat-10.1.23.zip
     dest: /opt
     mode: '0775'

  - name: Adding User Tomcat
    user:
     name: tomcat 

  - name: Extracting Tomcat Package
    unarchive:
     src: /opt/apache-tomcat-10.1.23.zip
     dest: /opt
     remote_src: yes

  - name: Change file ownership, group and permissions
    file:
     path: /opt/apache-tomcat-10.1.23
     owner: tomcat
     group: tomcat
     recurse: yes
    
  - name: Creating symbolic link
    file:
     src: /opt/apache-tomcat-10.1.23 
     dest: /usr/local/tomcat10
     owner: tomcat
     group: tomcat
     mode: '0775'
     state: link

  - name: Copying tomcat.service to systemd dir 
    copy: 
     src: /home/ec2-user/tomcat.service
     dest: /etc/systemd/system/

  - name: reloading systemctl
    systemd_service:
     state: restarted
     daemon_reload: true
     name: tomcat.service

  - name: chmod tomcat.service
    file:
     path: /etc/systemd/system/tomcat.service
     mode:  '0755'
  - name: start tomcat
    systemd:
     name: tomcat.service
     daemon_reload: yes
     enabled: yes
     state: started


...