---
- hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: Downloading Jenkins
    get_url:
     url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
     dest: /etc/yum.repos.d/jenkins.repo

  - name: Importing Jenkins Key
    shell: 
     cmd: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

  - name: Install Java 17
    yum: 
     name: java-17-openjdk
     state: present

  - name: Install Jenkins
    yum:
     name: jenkins
     state: present

  - name: Enableing and Starting Jenkins
    systemd_service:
     name: jenkins
     state: started
     enabled: true

...