---
- hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: Installing Unzip
    yum:
     name: unzip
     state: latest

  - name: Downloading TomcatServer....
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.23/bin/apache-tomcat-10.1.23.zip
     dest: /opt
     mode: '0775'

  - name: Adding User Tomcat
    user:
     name: tomcat 

  - name: Extracting Tomcat Package
    unarchive:
     src: /opt/apache-tomcat-10.1.23.zip
     dest: /opt
     remote_src: yes

  - name: Change file ownership, group and permissions
    file:
     path: /opt/apache-tomcat-10.1.23
     owner: tomcat
     group: tomcat
     recurse: yes

  - name: chmod for .sh file
    shell:
     cmd: chmod 755 *.sh
     chdir: /opt/apache-tomcat-10.1.23/bin

    
  - name: Creating symbolic link - Start
    file:
     src: /opt/apache-tomcat-10.1.23/bin/startup.sh  
     dest: /usr/bin/startTomcat
     owner: tomcat
     group: tomcat
     mode: '0775'
     state: link

  - name: Creating symbolic link - Stop
    file:
     src: /opt/apache-tomcat-10.1.23/bin/shutdown.sh   
     dest: /usr/bin/stopTomcat
     owner: tomcat
     group: tomcat
     mode: '0775'
     state: link

  - name: Starting Tomcat
    shell:
     cmd: startTomcat


...