---
- hosts: all
  become: true
  gather_facts: no

  tasks:
  - name: Install Unzip Server in Amazon Linux
    yum: 
     name: unzip
     state: latest

  - name: Download SonarQube In Amazon Linux
    get_url:
     url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-10.5.1.90531.zip
     dest: /home/ec2-user

  - name: Copying Files to /opt Directory
    copy:
     src: /home/ec2-user/sonarqube-10.5.1.90531.zip
     dest: /opt

  - name: Add Sonar User
    user:
     name: sonar 

  - name: Unzipping SonarQube File
    unarchive:
     src: /opt/sonarqube-10.5.1.90531.zip
     dest: /opt

  - name: changing name of sonarqube-10.5.1.90531 --> sonarqube
    shell:
     cmd: mv /opt/sonarqube-10.5.1.90531 /opt/sonarqube
     chdir: /opt

  - name: changing owner and group to sonar user
    file:
     path: /opt/sonarqube/
     owner: sonar
     group: sonar
     mode: '0775'

  - name: Starting SonarQube at Port No 9000
    shell:
     cmd: sh sonar.sh start
     chdir: /opt/sonarqube/bin/linux-x86-64/
...